language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g @angular/cli 

script:
  - ng build --base-href /my-awesome-project/
  - mv dist/my-awesome-project/index.html dist/my-awesome-project/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/my-awesome-project
  on:
    branch: master
 